### PR TITLE
quick and merge sort implementation in java

### PR DESCRIPTION
**Pull request by Amitsharma45**
issue #29

### CODE REVIEW

**Comment by Amitsharma45** [comment]
@tornado-12 please add "hacktoberfest-accepted" label to it.

**Comment by Amitsharma45** [comment]
@tornado-12 please add  hacktoberfest topic in a repo and add hacktoberfest-accepted

**Comment by Amitsharma45** [comment]
@tornado-12 please add hacktoberfest topic in a repo and add hacktoberfest-accepted

**Comment by tornado-12** [comment]
@Amitsharma45 i have added hacktoberfest topic in repository

**Pull request merged**
